server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:4000/authdb
    username: root
    password: sefa1220504
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

app:
  jwt-secret: "7C2F9A338F7F55DF7D8E8EBBE1405A659A06731A44D482FAABAD54FF293CFB79"
  jwt-expiration: 86400000
  refresh-token:
    jwt-expiration: 604800000


management:
  endpoints:
    web:
      exposure:
        include: "*"
