server:
  port: 8900
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/favouritesdb
    username: root
    password: sefa1220504
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
