spring:
    datasource:
        url: jdbc:mysql://localhost:3306/shippingdb
        username: root
        password: sefa1220504
    jpa:
        hibernate:
            ddl-auto: update
    main:
        allow-bean-definition-overriding: true
server:
    port: 8800
