server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: sefa1220504
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  boot:
    message: "aleyküm selam"
